[project]
name = "saestories"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "einops",
    "datasets>=3.5.0",
    "transformer-lens>=2.15.0",
    "sentencepiece>=0.2.0",
]
